title: Elijah O. Adebola Data Analytics portfolio
logo: Headshot.png
description: An excellent data analyst with multiple years of experience with Advanced Microsoft Excel, SQL, Python, R and Power BI.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
