title: Elijah O. Adebola Data Analytics portfolio
logo: passport new.jpeg
description: An excellent data analyst with multiple years of experience and proficiency with tools such as Advanced Microsoft Excel, SQL, Python, R and Power BI.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
